# Configuration for Rasa NLU.
language: "en"
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "RegexFeaturizer"
- name: "SpacyFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"
- name: "components.intent_information.IntentInformation"

# Configuration for Rasa Core.
policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: MemoizationPolicy
    max_history: 5
  - name: MappingPolicy
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'

