version: '3.0'

services:
  rasa_core:
    image: aroemelt/ethicbot:core
    ports:
      - 5000:5005
    volumes:
      - ./models/rasa_core:/app/models
      - ./config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - socketio
      - --endpoints
      - config/endpoints.yml
      - -u
      - current/
  rasa_nlu:
    image: aroemelt/ethicbot:nlu
    volumes:
      - ./models/rasa_nlu:/app/models
      - ./config:/app/config
      - ./components:/app/components
      - ./modules:/app/modules
    command:
      - start
      - --path
      - models
      - -c
      - config/nlu_config.yml
  action_server:
    image: aroemelt/ethicbot:actions
    volumes:
      - ./actions:/app/actions
      - ./modules:/app/modules