version: '3.0'

services:
  rasa:
    image: aroemelt/ethicbot:rasa
    expose:
      - 5005
    volumes:
      - ./:/app
    command:
      - run
      - --connector
      - socketio
      - --debug
  action_server:
    image: aroemelt/ethicbot:actions
    volumes:
      - ./actions:/app/actions
      - ./modules:/app/modules
      - ./data:/app/data
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverseproxy/nginx:/etc/nginx/conf.d
      - ./reverseproxy/certbot/conf:/etc/letsencrypt
      - ./reverseproxy/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./reverseproxy/certbot/conf:/etc/letsencrypt
      - ./reverseproxy/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"