version: '3.0'

services:
  rasa:
    image: aroemelt/ethicbot:rasa
    ports:
      - 8080:5005
    volumes:
      - ./:/app
    command:
      - run
      - --connector
      - socketio
      - --endpoints
      - config/endpoints.yml
  action_server:
    image: aroemelt/ethicbot:actions
    volumes:
      - ./actions:/app/actions
      - ./modules:/app/modules