nlu:
  url: http://rasa_nlu:5000
action_endpoint:
  url: http://action_server:5055/webhook
tracker_store:
  store_type: mongod
  url: mongodb+srv://ethicstore-dbmzc.mongodb.net
  db: rasa
  collection: conversations
  username: rasa
  password: asar